main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.home, name='home'),
  path('about/', views.about, name='about'),
  path('movies/', views.movies_index, name='index'),
  path('movies/<int:movie_id>/', views.movies_detail, name = 'detail'),
  path('movies/create/', views.MovieCreate.as_view(), name='movies_create'),
  path('movies/<int:pk>/update/', views.MovieUpdate.as_view(), name='movies_update'),
  path('movies/<int:pk>/delete/', views.MovieDelete.as_view(), name='movies_delete'),
  path('movies/<int:movie_id>/add_rental/', views.add_rental, name='add_rental'),
  path('movies/<int:movie_id>/assoc_snack/<int:snack_id>/', views.assoc_snack, name='assoc_snack'),

]

moviecollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('main_app.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse

LOCATION = (
    ('U', 'Upstairs Media Room'),
    ('D', 'Downstairs Living Room'),
    ('B', 'Borrowed')
)

class Snack(models.Model):
    name = models.CharField(max_length=50)
    style = models.CharField(max_length=100)

class Movie(models.Model):  # Note that parents are optional if not inheriting from another class
    name = models.CharField(max_length=100)
    genre =  models.CharField(max_length=100)
    location =  models.CharField(
        max_length=1,
        choices=LOCATION,
        default=LOCATION[0][0],
        )
    series = models.CharField(max_length=100)
    stock = models.IntegerField()
    snacks = models.ManyToManyField(Snack)

    def __str__(self):
        return f"Movie: {self.name}. ID: {self.id}."
    
    def get_absolute_url(self):

        return reverse('detail', kwargs={'movie_id': self.id})

STATUS = (
    ('O', 'Outstanding'),
    ('L', 'Late'),
    ('R', 'Returned'),
    ('D', 'Damaged'),
    ('V', 'Resolved'),
)

class Rental(models.Model):
    name = models.CharField(max_length=100)
    date = models.DateField('rental date')
    returned = models.CharField(
        max_length=1,
        choices=STATUS,
        default=STATUS[0][0]
    )

    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

    def __str__(self):
        return f"Renter Name: {self.name}. ID: {self.id}."
    
    class Meta:
        ordering = ['-date']

# class Person(models.Model):
#     name = models.CharField(max_length=50)
#     phone = models.IntegerField()
#     rentals = models.ManyToManyField(Rental)
    
#     def __str__(self):
#         return self.name

#     def get_absolute_url(self):
#         return reverse('people_detail', kwargs={'pk': self.id})


        
# class Borrowers (for a many to many maybe?)

main_app/forms.py
from django.forms import ModelForm
from .models import Rental

class RentalForm(ModelForm):
  class Meta:
    model = Rental
    fields = ['name', 'date','returned']

main_app/views.py
from django.shortcuts import render, redirect

# Add the following import
from django.http import HttpResponse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Movie, Snack
from .forms import RentalForm


# This is no longer needed once the models.py part is used.
# class Movie:  # Note that parents are optional if not inheriting from another class
#   def __init__(self, name, genre, location, series, stock):
#     self.name = name
#     self.genre = genre
#     self.location = location
#     self.series = series
#     self.stock = stock

# movies = [
#   Movie('Avengers', 'Action', 'Upstairs', 'Marvel', 1),
#   Movie('Spiderman', 'Action', 'Downstairs', 'Marvel', 1),
#   Movie('Stardust', 'Action', 'Matt Rented', '', 2)
# ]

class MovieCreate(CreateView):
  model = Movie
  fields = '__all__'

class MovieUpdate(UpdateView):
  model = Movie
  fields = ['genre', 'location', 'series','stock']

class MovieDelete(DeleteView):
  model = Movie
  success_url = '/movies/'

# Define the home view
def home(request):
    return render(request, 'base.html')

def about(request):
    return render(request, 'about.html')

def movies_index(request):
  movies = Movie.objects.all()
  return render(request, 'movies/index.html', { 'movies': movies })

def movies_detail(request, movie_id):
  movie = Movie.objects.get(id=movie_id)
  lonely_snacks = Snack.objects.exclude(id__in = movie.snacks.all().values_list('id'))
  rental_form = RentalForm()
  return render(request, 'movies/detail.html', {'movie': movie, 'rental_form': rental_form, 'snacks': lonely_snacks})

def add_rental(request, movie_id):
   # create a ModelForm instance using the data in request.POST
  form = RentalForm(request.POST)
  # validate the form
  if form.is_valid():
    # don't save the form to the db until it
    # has the cat_id assigned
    new_rental = form.save(commit=False)
    new_rental.movie_id = movie_id
    new_rental.save()
  return redirect('detail', movie_id=movie_id)

def assoc_snack(request, movie_id, snack_id):
  # Note that you can pass a toy's id instead of the whole object
  Movie.objects.get(id=movie_id).snacks.add(snack_id)
  return redirect('detail', movie_id=movie_id)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Movie Collector</h1>
<hr />
<p>Hire the Movie Collector!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Movie Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;MovieCollector</a></li>
          
        </ul>
        <ul class="right">
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'movies_create' %}">Add Movie</a></li>
            <li><a href="{% url 'index' %}">View All My Movies</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2022 Movie Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/main_app/movie_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Movie</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' movie.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/movie_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Movie</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/movies/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Movie Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ movie.name }}</span>
        <p>Genre: {{ movie.breed }}</p>
        <p>Series: {{ movie.description }}</p>
        <p>Location: {{ movie.location }}</p>
        {% if movie.stock > 0 %}
            <p>In Stock</p>
        {% else %}
            <p>Not here, is it rented?</p>
        {% endif %}
      </div>
      <div class="card-action">
        <a href="{% url 'movies_update' movie.id %}">Edit</a>
        <a href="{% url 'movies_delete' movie.id %}">Delete</a>
      </div>
    </div>
  </div>
  <div class="col s6">
    <form  action="{% url 'add_rental' movie.id %}" method="post">
        {% csrf_token %}
        {{ rental_form.as_p }}
        <input type="submit" class="btn" value="Add Rental">
      </form>
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Name</th><th>Status</th></tr>
      </thead>
      <tbody>
        {% for rental in movie.rental_set.all %}
          <tr>
            <td>{{rental.date}}</td>
            <td>{{rental.name}}</td>
            <td>{{rental.get_returned_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ movie.name }}'s Recommended Snacks</h3>
    {% if movie.snacks.count %}
      {% for snack in movie.snacks.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              Try some: {{ snack.name }} a {{ snack.style }} treat!
            </span>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Recommended Snacks... :-(</h5>
    {% endif %}
  </div>
</div>
  <div class="col s6">
    <h3>Available Snacks</h3>
    {% if snacks.count %}
      {% for snack in snacks.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              {{ snack.name }} a {{ snack.style }} treat!
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_snack' movie.id snack.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{movie.name}} Already Has All Snacks Available</h5>
    {% endif %}
  </div>
</div>
<script>
    const dateEl = document.getElementById('id_date');
    M.Datepicker.init(dateEl, {
      format: 'yyyy-mm-dd',
      defaultDate: new Date(),
      setDefaultDate: true,
      autoClose: true
    });

    const selectEl = document.getElementById('id_returned');
    M.FormSelect.init(selectEl);

</script>
  
{% endblock %}

main_app/templates/movies/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Movie List</h1>

{% for movie in movies %}
  <div class="card">
    <a href="{% url 'detail' movie.id %}">
     <div class="card-content">
       <span class="card-title">{{ movie.name }}</span>
        <p>Genre: {{ movie.genre }}</p>
        <p>Series: {{ movie.series }}</p>
       <p>Location: {{ movie.location }}</p>
        {% if movie.stock > 0 %}
          <p>In Stock</p>
        {% else %}
          <p>Not here, is it rented?</p>
        {% endif %}
      </div>
    </a>
  </div>

{% endfor %}

{% endblock %}